# Generated by Django 3.2.7 on 2021-10-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_singleimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepool',
            old_name='name',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='imagepool',
            name='risk',
            field=models.FloatField(default=99.9),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
