# Generated by Django 3.2.7 on 2021-10-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211012_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepool',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagepool',
            name='risk',
            field=models.FloatField(blank=True),
        ),
    ]
