# Generated by Django 3.2.7 on 2021-10-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211016_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
