# Generated by Django 3.2.9 on 2021-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_imagepool_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepool',
            name='heatmap',
            field=models.ImageField(default=0, upload_to='heatmaps/'),
            preserve_default=False,
        ),
    ]
