# Generated by Django 3.2.9 on 2021-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_imagepool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepool',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
