# Generated by Django 3.2.9 on 2021-11-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_imagepool_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepool',
            name='risk_class',
        ),
    ]
